.TH "auxiliaryFunctions" 3 "Tue Mar 23 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auxiliaryFunctions \- Auxiliary functions to check
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "declare i \fBARRAY_LENGTH\fP \fBcreate_options_array\fP ()"
.br
.RI "Read file \fBoptions\fP into a temporary array A which will contain command line specifications\&. "
.ti -1c
.RI "\fBcheck_md5sum\fP (filename)"
.br
.RI "Check md5sums in file MD5SUMS\&. "
.ti -1c
.RI "\fBtest_numeric\fP (number)"
.br
.RI "Test whether the input value is numeric\&. "
.ti -1c
.RI "\fBtest_URL\fP (Internet)"
.br
.RI "Test whether the input value is a valid URL\&. "
.ti -1c
.RI "\fBsend_mail\fP ()"
.br
.RI "Send an email to $EMAIL at $SMTP_URL to warn about end of processing\&. "
.ti -1c
.RI "\fBrecreate_liveCD_ISO\fP (dir)"
.br
.RI "Create ISO of liveCD out of directory\&. "
.ti -1c
.RI "\fBburn_iso\fP ()"
.br
.RI "Burn Gentoo clonezilla installer to DVD using \fBcdrecord\fP\&. "
.ti -1c
.RI "\fBcreate_install_ext_device\fP ()"
.br
.RI "Create USB-stick (or any external device) Gentoo clonezilla installer\&. "
.ti -1c
.RI "\fBcheck_dir\fP ()"
.br
.RI "Checks existence of directories\&. "
.ti -1c
.RI "\fBcheck_file\fP ()"
.br
.RI "Checks existence of file\&. "
.ti -1c
.RI "\fBcheck_files\fP ()"
.br
.RI "Checks existence of files\&. "
.ti -1c
.RI "\fBcheck_tool\fP ()"
.br
.RI "Checks existence of auxiliary tools\&. "
.ti -1c
.RI "\fBif_fails\fP ()"
.br
.RI "Echoes a message and exit in case of previous command failure\&. "
.ti -1c
.RI "\fBcleanup\fP ()"
.br
.RI "Clean up all temporary files and directpries (except for VirtualBox build) "
.ti -1c
.RI "\fBbind_filesystem\fP (root)"
.br
.RI "Bind-mounts the host live filesystem (proc/sys/dev/run) to a future chrooted OS-like tree of similar nature\&. "
.in -1c
.SH "Detailed Description"
.PP 
lines, files, devices and burn disk\&. 
.SH "Function Documentation"
.PP 
.SS "bind_filesystem (root)"

.PP
Bind-mounts the host live filesystem (proc/sys/dev/run) to a future chrooted OS-like tree of similar nature\&. 
.PP
\fBParameters\fP
.RS 4
\fIroot\fP Root directory of the subordinate filesystem\&. 
.RE
.PP

.PP
Definition at line 520 of file utils\&.sh\&.
.SS "burn_iso ()"

.PP
Burn Gentoo clonezilla installer to DVD using \fBcdrecord\fP\&. 
.PP
\fBNote\fP
.RS 4
\fBcdrecord\fP should have been installed beforehand 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIReturn\fP \fBcdrecord\fP return code 
.RE
.PP

.PP
Definition at line 310 of file utils\&.sh\&.
.SS "check_dir ()"

.PP
Checks existence of directories\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirs\fP Successive paths (relative or absolute) to directories\&. 
.RE
.PP
\fBWarning\fP
.RS 4
Paths should be separated by spaces and quoted\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUndefined\fP or exit 2 if string is not a directory path 
.RE
.PP

.PP
Definition at line 388 of file utils\&.sh\&.
.SS "check_file ()"

.PP
Checks existence of file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilepath\fP Relative or absolute path to file to be checked for existence\&. 
.br
\fImsgs\fP Successive message strings to be echoed if file not found\&. 
.RE
.PP
\fBWarning\fP
.RS 4
Paths should be separated by spaces and quoted\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUndefined\fP or exit 3 if string is not a file path 
.RE
.PP

.PP
Definition at line 409 of file utils\&.sh\&.
.SS "check_files ()"

.PP
Checks existence of files\&. 
.PP
\fBParameters\fP
.RS 4
\fIfiles\fP Successive paths (relative or absolute) to files\&. 
.RE
.PP
\fBWarning\fP
.RS 4
Paths should be separated by spaces and quoted\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUndefined\fP or exit 3 if any string is not a file path 
.RE
.PP

.PP
Definition at line 429 of file utils\&.sh\&.
.SS "check_md5sum (filename)"

.PP
Check md5sums in file MD5SUMS\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Local name of file to be checked for md5sum\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIReturn\fP 0 on success otherwise -1 on exit 
.RE
.PP

.PP
Definition at line 93 of file utils\&.sh\&.
.SS "check_tool ()"

.PP
Checks existence of auxiliary tools\&. 
.PP
\fBParameters\fP
.RS 4
\fIdirs\fP Successive paths (relative or absolute) to helper binaries\&. 
.RE
.PP
\fBWarning\fP
.RS 4
Paths should be separated by spaces and quoted\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUndefined\fP or exit 1 if binary not found\&. 
.RE
.PP

.PP
Definition at line 449 of file utils\&.sh\&.
.SS "cleanup ()"

.PP
Clean up all temporary files and directpries (except for VirtualBox build) Needs
.PP
.nf
CLEANUP=true 

.fi
.PP
\&. If
.PP
.nf
FULL_CLEANUP=true

.fi
.PP
 then erase ISO files with names containing \fBclonezilla\fP, \fBinstall\fP or \fBdownloaded\fP names\&. 
.PP
Definition at line 491 of file utils\&.sh\&.
.SS "create_install_ext_device ()"

.PP
Create USB-stick (or any external device) Gentoo clonezilla installer\&. 
.PP
\fBWarning\fP
.RS 4
Use with care, check your EXT_DEVICE variable\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIReturn\fP value of \fCsync\fPexit code 
.RE
.PP

.PP
Definition at line 360 of file utils\&.sh\&.
.SS "create_options_array ()"

.PP
Read file \fBoptions\fP into a temporary array A which will contain command line specifications\&. Later on A initializes the read-only array \fBARR\fP 
.PP
Definition at line 71 of file utils\&.sh\&.
.SS "if_fails ()"

.PP
Echoes a message and exit in case of previous command failure\&. 
.PP
\fBParameters\fP
.RS 4
\fIret\fP Return value of command to be tested\&. 
.br
\fImsg\fP \&.\&.\&. Message(s) to be echoed inc case of a failure\&. 
.RE
.PP
\fBNote\fP
.RS 4
Command success is presumed to be identified by $? == 0\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIUndefined\fP or exit 1 if $? != 0\&. 
.RE
.PP

.PP
Definition at line 470 of file utils\&.sh\&.
.SS "recreate_liveCD_ISO (dir)"

.PP
Create ISO of liveCD out of directory\&. 
.PP
\fBParameters\fP
.RS 4
\fIdir\fP Directory containing all files 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success or exits -1 on failure\&. 
.RE
.PP
\fBNote\fP
.RS 4
An alternative xorriso solution could be considered 
.RE
.PP

.PP
Definition at line 271 of file utils\&.sh\&.
.SS "send_mail ()"

.PP
Send an email to $EMAIL at $SMTP_URL to warn about end of processing\&. 
.PP
\fBWarning\fP
.RS 4
Email password is entered in clear using $EMAIL_PASSWD which is not safe if mkg is run on any other platform than the user's own\&. Use with care in a private context\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Return value of `curl' command\&. 
.RE
.PP

.PP
Definition at line 133 of file utils\&.sh\&.
.SS "test_numeric (number)"

.PP
Test whether the input value is numeric\&. 
.PP
\fBParameters\fP
.RS 4
\fInumber\fP in string form 
.RE
.PP
\fBReturns\fP
.RS 4
grep value against input string 
.RE
.PP

.PP
Definition at line 109 of file utils\&.sh\&.
.SS "test_URL (Internet)"

.PP
Test whether the input value is a valid URL\&. 
.PP
\fBParameters\fP
.RS 4
\fIInternet\fP URL 
.RE
.PP
\fBReturns\fP
.RS 4
grep value against input string 
.RE
.PP

.PP
Definition at line 119 of file utils\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
