.TH "bug" 3 "Wed Sep 30 2020" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBGlobal \fBpartition\fP ()\fP" 1c
Same issue with mkswap and swapon\&. Cleaning VBox config/settings, syncing and a bit of sleep fixed these issues for the \fInet-setup\fP method\&. 
.PP
However the \fIdhcpcd\fP method is consistently broken, which currently blocks headless vmtypes\&. 
.PP

