.TH "bug" 3 "Sun Mar 21 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBGlobal \fBcreate_vm\fP (VM)\fP" 1c
VB bug note Unfortunately 
.IP "\fBGlobal \fBpartition\fP ()\fP" 1c
Same issue with mkswap and swapon\&. Cleaning VBox config/settings, syncing and a bit of sleep fixed these issues for the \fInet-setup\fP method\&. 
.PP
However if vm type is \fI'headless'\fP the \fIdhcpcd\fP method is consistently hampered by a VBox bug, which is tentatively circumvented by sending a \fCcontrolvm keyboardputscancode 1c\fP instruction\&. Tests show that this is linked to a requested user keyboard or mouse input by the Gentoo minimal install CD\&. This cannot be simulated owing to the lack of /dev/uinput\&. The reason why user input is requested has not been found\&. Without it, /dev/sda2 and/or sda4 are mistakenly identified as being mounted and/or busy, while this cannot be the case\&. With even a single keystroke for a \fCread\fPcommand, all falls back into place\&. This is why using the net-setup script, which forces user input, circumvents the issue\&. This may be caused by an aging kernel and/or incompatibilities with virtualization\&. Using a CloneZilla CD as a replacement solved the issue completely\&. It might be better to use a beefed-up Gentoo install CD\&. 
.PP

