.TH "build_virtualbox.sh" 3 "Sun Feb 14 2021" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build_virtualbox.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBDOWNLOAD_CLONEZILLA\fP = 'true'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DOWNLOAD_CLONEZILLA = 'true'"

.PP
Definition at line 10 of file build_virtualbox\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gentoo-creator from the source code\&.
