.TH "build_virtualbox.sh" 3 "Mon Mar 15 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build_virtualbox.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbuild_virtualbox\fP ()"
.br
.RI "Build VirtualBox from source using an unsquashed clonezilla CD as a chrooted environment\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBDEBIAN_FRONTEND\fP = noninteractive"
.br
.ti -1c
.RI "Exported String \fBLD_LIBRARY_PATH\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DEBIAN_FRONTEND = noninteractive"

.PP
Definition at line 27 of file build_virtualbox\&.sh\&.
.SS "Exported String LD_LIBRARY_PATH"
\fBInitial value:\fP
.PP
.nf
= "virtualbox/VirtualBox/out/linux\&.amd64/release/bin/\;








Exported String LD_LIBRARY_PATH = "virtualbox/VirtualBox/out/linux\&.amd64/release/bin/\
.fi
.PP
Definition at line 89 of file build_virtualbox\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
