.TH "build_virtualbox.sh" 3 "Mon Sep 28 2020" "Version 1.0" "mkgentoo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build_virtualbox.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVMPATH\fP = $PWD/\&.\&."
.br
.ti -1c
.RI "Exported String \fBDOWNLOAD_CLONEZILLA\fP = 'true'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DOWNLOAD_CLONEZILLA = 'true'"

.PP
Definition at line 3 of file build_virtualbox\&.sh\&.
.SS "Exported String VMPATH = $PWD/\&.\&."

.PP
Definition at line 2 of file build_virtualbox\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkgentoo from the source code\&.
