.TH "createInstaller" 3 "Sun Mar 21 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
createInstaller
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbuild_virtualbox\fP ()"
.br
.RI "Build VirtualBox from source using an unsquashed clonezilla CD as a chrooted environment\&. "
.ti -1c
.RI "\fBhelp_md\fP ()"
.br
.RI "Print usage in markdown format\&. "
.ti -1c
.RI "\fBhelp_\fP ()"
.br
.RI "Print usage to stdout\&. "
.ti -1c
.RI "\fBmanpage\fP ()"
.br
.RI "Print help to man page\&. "
.ti -1c
.RI "\fBhtmlpage\fP ()"
.br
.RI "Print help to html page\&. "
.ti -1c
.RI "\fBpdfpage\fP ()"
.br
.RI "Print help to pdf page\&. "
.ti -1c
.RI "\fBvalidate_option\fP (option)"
.br
.RI "Check if argument is part of array \fBARR\fP as a legitimate commandline option\&. "
.ti -1c
.RI "\fBget_options\fP ()"
.br
.RI "Parse command line\&. "
.ti -1c
.RI "\fBtest_cli_pre\fP ()"
.br
.RI "Check VirtualBox version and prepare commandline analysis\&. "
.ti -1c
.RI "\fBtest_cli\fP (cli)"
.br
.RI "Analyse commandline\&. "
.ti -1c
.RI "\fBtest_cli_post\fP ()"
.br
.RI "Check commanline coherence and incompatibilities\&. "
.ti -1c
.RI "\fBmount_live_cd\fP ()"
.br
.RI "Mount Gentoo/Clonezilla live CD and unsquashfs the GNU/linux system\&. "
.ti -1c
.RI "\fBmake_boot_from_livecd\fP ()"
.br
.RI "Tweak the Gentoo minimal install CD so that the custom- made shell scripts and stage3 archive are included into the squashfs filesystem\&. "
.ti -1c
.RI "\fBtest_vm_running\fP (vm)"
.br
.RI "Check if VM as first named argument exists and is running\&. "
.ti -1c
.RI "\fBdeep_clean\fP ()"
.br
.RI "Force-clean root VirtualBox registry\&. "
.ti -1c
.RI "\fBdelete_vm\fP (vm, ext, mode)"
.br
.RI "Powers off, possibly with emergency stop, the VM names as first argument\&. "
.ti -1c
.RI "\fBcreate_vm\fP (VM)"
.br
.RI "Create main VirtualBox machine using VBoxManage commandline\&. "
.ti -1c
.RI "\fBlog_loop\fP ()"
.br
.RI "Loop log tags every minute and optionally plot virtual disk size\&. "
.ti -1c
.RI "\fBcreate_iso_vm\fP ()"
.br
.RI "Create the new VirtualBox machine aimed at converting the VDI virtualdisk containing the Gentoo Linux distribution into an XZ-compressed clonezilla image uneder \fBISOFILES/home/partimag/image\fP\&. "
.ti -1c
.RI "\fBclone_vm_to_device\fP (mode)"
.br
.RI "Directly clone Gentoo VM to USB stick (or any using block device) "
.ti -1c
.RI "\fBcreate_device_system\fP (Mode)"
.br
.RI "Clone VDI virtual disk to external device (USB device or hard drive) "
.ti -1c
.RI "\fBclonezilla_to_iso\fP (iso, dir)"
.br
.RI "Create Gentoo linux clonezilla ISO installer out of a clonezilla directory structure and an clonezilla image\&. "
.ti -1c
.RI "\fBadd_guest_additions_to_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO or recover it from cache calling \fBfetch_process_clonezilla_iso\fP\&. 
.br
Upgrade it with virtualbox guest additions\&. "
.ti -1c
.RI "\fBbind_mount_clonezilla_iso\fP ()"
.br
.RI "Fetches the clonezilla ISO\&. mount it to mnt, rsync it to mnt2 and ISOFILES bind-mount mnt2 live filesystem after unsquashfs\&. "
.ti -1c
.RI "\fBunmount_clonezilla_iso\fP ()"
.br
.RI "Unmount the clonezilla filesystem after exiting chroot\&. Restore the squashfs filesystem\&. "
.ti -1c
.RI "\fBclonezilla_device_to_image\fP ()"
.br
.RI "Create CloneZilla xz-compressed image out of an external block device (like a USB stick) "
.ti -1c
.RI "\fBprepare_for_iso_vm\fP ()"
.br
.ti -1c
.RI "\fBgenerate_Gentoo\fP ()"
.br
.RI "Launch routines: fetch install IO, starge3 archive, create VM\&. "
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Main function launching routines\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBISO\fP = 'downloaded\&.iso'"
.br
.RI "Name of downloaded clonezilla ISO file\&. "
.ti -1c
.RI "Exported String \fBCREATE_ISO\fP = false"
.br
.RI "Custom name of ISO output\&. Default value is false Can be reversed by a name of type filename\&.iso on command line, previously created and reused to burn or dd to device installer\&. "
.ti -1c
.RI "Exported String \fBARR\fP"
.br
.RI "global string array of switches and default values "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "add_guest_additions_to_clonezilla_iso ()"

.PP
Download clonezilla ISO or recover it from cache calling \fBfetch_process_clonezilla_iso\fP\&. 
.br
Upgrade it with virtualbox guest additions\&. Chroot into the clonezilla Ubuntu GNU/Linux distribution and runs apt to build kernel modules and install the VirtualBox guest additions ISO image\&. 
.br
Upgrade clonezilla kernel consequently Recreates the quashfs system after exiting chroot\&. Copy the new \fBisolinux\&.cfg\fP parameter file: automates and silences clonezilla behaviour on disk recovery\&. Calls \fBclonezilla_to_iso\fP 
.PP
\fBNote\fP
.RS 4
Installing the guest additions is a prerequisite to folder sharing between the ISO VM and the host\&. Folder sharing is necessary to recover a compressed clonezilla image of the VDI virtual disk into the directory ISOFILES/home/partimag/image 
.RE
.PP

.PP
Definition at line 2067 of file mkgentoo\&.sh\&.
.SS "bind_mount_clonezilla_iso ()"

.PP
Fetches the clonezilla ISO\&. mount it to mnt, rsync it to mnt2 and ISOFILES bind-mount mnt2 live filesystem after unsquashfs\&. 
.PP
Definition at line 2138 of file mkgentoo\&.sh\&.
.SS "build_virtualbox ()"

.PP
Build VirtualBox from source using an unsquashed clonezilla CD as a chrooted environment\&. Build scripts are copied from \fBclonezilla/build\fP 
.PP
Definition at line 30 of file build_virtualbox\&.sh\&.
.SS "clone_vm_to_device (mode)"

.PP
Directly clone Gentoo VM to USB stick (or any using block device) 
.PP
\fBParameters\fP
.RS 4
\fImode\fP Either 'qemu' or 'guestfish' 
.RE
.PP

.PP
Definition at line 1935 of file mkgentoo\&.sh\&.
.SS "clonezilla_device_to_image ()"

.PP
Create CloneZilla xz-compressed image out of an external block device (like a USB stick) Image is created under ISOFILES/home/partimag/image under VMPATH 
.PP
\fBReturn values\fP
.RS 4
\fI0\fP on success otherwise exits -1 on failure 
.RE
.PP

.PP
Definition at line 2209 of file mkgentoo\&.sh\&.
.SS "clonezilla_to_iso (iso, dir)"

.PP
Create Gentoo linux clonezilla ISO installer out of a clonezilla directory structure and an clonezilla image\&. 
.PP
\fBParameters\fP
.RS 4
\fIiso\fP ISO output 
.br
\fIdir\fP Directory to be transformed into ISO output 
.RE
.PP
\fBNote\fP
.RS 4
ISO can be burned to DVD or used to create a bootable USB stick using dd on *nix platforms or Rufus (on Windows)\&. 
.RE
.PP

.PP
Definition at line 2017 of file mkgentoo\&.sh\&.
.SS "create_device_system (Mode)"

.PP
Clone VDI virtual disk to external device (USB device or hard drive) Two options are available, qemu or guestfish\&. 
.PP
\fBParameters\fP
.RS 4
\fIMode\fP Mode must be qemu or guestfish\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fI0\fP on success, 1 on error\&. 
.RE
.PP
\fBNote\fP
.RS 4
Requires \fBhot_install\fP on command line to be activated as a security confirmation\&. This function performs what a live CD does to a target disk, yet using the currently running operating system\&. 
.RE
.PP

.PP
Definition at line 1987 of file mkgentoo\&.sh\&.
.SS "create_iso_vm ()"

.PP
Create the new VirtualBox machine aimed at converting the VDI virtualdisk containing the Gentoo Linux distribution into an XZ-compressed clonezilla image uneder \fBISOFILES/home/partimag/image\fP\&. Register machine, create VDI drive, create IDE drive attach disks to controlers 
.br
Attach newly augmented clonezilla LiveCD to IDE controller\&. 
.br
Wait for the VM to complete its task\&. Check that it is still running every minute\&. 
.br
\fBNote\fP
.RS 4
VM may be visible (vm type=gui) or silent (vm type=headless, currently to be fixed)\&. Wait for the VM to complete task\&. 
.br
A new VM is necessary as the first VM used to build the Gentoo filesystem does not contain clonezilla or the VirtualBox guest additions (requested for sharing folders with host)\&. Calls \fBadd_guest_additions_to_clonezilla_iso\fP to satisfy these requirements\&. 
.RE
.PP
\fBWarning\fP
.RS 4
the \fBsharedfolder\fP command may fail vith older version of VirtualBox or not be implemented\&. It is transient, so it disappears on shutdown and requests prior startup of VM to be activated\&. 
.RE
.PP

.PP
Definition at line 1646 of file mkgentoo\&.sh\&.
.SS "create_vm (VM)"

.PP
Create main VirtualBox machine using VBoxManage commandline\&. 
.PD 0

.IP "\(bu" 2
Register machine, create VDI drive, create IDE drive attach disks to controlers 
.IP "\(bu" 2
Attach augmented clonezilla LiveCD to IDE controller\&. 
.IP "\(bu" 2
Wait for the VM to complete its task\&. Check that it is still running every minute\&. 
.IP "\(bu" 2
Finally compact it\&. 
.PP
\fBParameters\fP
.RS 4
\fIVM\fP Name of the virtual machine\&. 
.RE
.PP
\fBNote\fP
.RS 4
VM may be visible (vm type=gui) or without GUI (vm type=headless, currently to be fixed) 
.RE
.PP
\fBBug\fP
.RS 4
VB bug note Unfortunately
.RE
.PP
.PP
.nf
 VBoxManage modifyvm --cpu-profile host @encode
is not fail-safe\&.
For example, this option detects my CPU (Intel core-i7 5820K) vendor,
model name, number of cpus etc\&. yet the list of flags is erroneous
and does not contain flags **fma, bmi, bmi2** necessary to compile with
@code -march=haswell 
.fi
.PP
\&. The guest \fB/proc/cpuinfo\fP lacks these flags, which are listed in the host /proc/cpuinfo, so the VB flag import capability is buggy or incomplete\&. Borrowing partial solution from: https://superuser.com/questions/625648/ virtualbox-how-to-force-a-specific-cpu-to-the-guest This added code does not unfortunately enables -march=haswell (+) 
.PP
\fBTodo\fP
.RS 4
Find a way to only compact on success and never on failure of VM\&. 
.RE
.PP

.PP

.PP
Definition at line 1386 of file mkgentoo\&.sh\&.
.SS "deep_clean ()"

.PP
Force-clean root VirtualBox registry\&. 
.PP
Definition at line 1216 of file mkgentoo\&.sh\&.
.SS "delete_vm (vm, ext, mode)"

.PP
Powers off, possibly with emergency stop, the VM names as first argument\&. 
.PP
\fBParameters\fP
.RS 4
\fIvm\fP VM name 
.br
\fIext\fP virtual disk extension, without dot (defaults to 'vdi')\&. 
.br
\fImode\fP '' for standard VM or 'ISO_STAGE' for ISO-creating VM\&.
.RE
.PP
.PD 0
.IP "\(bu" 2
Unregisters it 
.IP "\(bu" 2
Deletes its folder structure and hard drive (default is 'vdi' as a second argument) 
.PP
\fBReturn values\fP
.RS 4
\fIReturns\fP 0 if Directory and hard drive could be erased, otherwise the OR value of both erasing commands 
.RE
.PP

.PP

.PP
Definition at line 1273 of file mkgentoo\&.sh\&.
.SS "generate_Gentoo ()"

.PP
Launch routines: fetch install IO, starge3 archive, create VM\&. 
.PP
Definition at line 2345 of file mkgentoo\&.sh\&.
.SS "get_options ()"

.PP
Parse command line\&. 
.PP
Definition at line 281 of file mkgentoo\&.sh\&.
.SS "help_ ()"

.PP
Print usage to stdout\&. 
.PP
Definition at line 226 of file mkgentoo\&.sh\&.
.SS "help_md ()"

.PP
Print usage in markdown format\&. 
.PP
\fBNote\fP
.RS 4
white space at end of echoes is there for markdown in post-processing 
.RE
.PP

.PP
Definition at line 124 of file mkgentoo\&.sh\&.
.SS "htmlpage ()"

.PP
Print help to html page\&. 
.PP
Definition at line 243 of file mkgentoo\&.sh\&.
.SS "log_loop ()"

.PP
Loop log tags every minute and optionally plot virtual disk size\&. Customizable suing options: plot_color, plot_period, plot_position, plot_pause, plot_span 
.PP
Definition at line 1570 of file mkgentoo\&.sh\&.
.SS "main ()"

.PP
Main function launching routines\&. 
.PP
\fBTodo\fP
.RS 4
Daemonize the part below generate_Gentoo when #VMTYPE is \fCheadless\fP so that the script can be detached completely with \fCnohup mkgentoo\&.\&. &\fP 
.RE
.PP

.PP
Definition at line 2395 of file mkgentoo\&.sh\&.
.SS "make_boot_from_livecd ()"

.PP
Tweak the Gentoo minimal install CD so that the custom- made shell scripts and stage3 archive are included into the squashfs filesystem\&. This function is returned from early if
.PP
.nf
create_squashfs=false

.fi
.PP
 is given on commandline\&. 
.PP
\fBNote\fP
.RS 4
Will be run in the ${VM} virtual machine 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIReturns\fP 0 on success or -1 on failure\&. 
.RE
.PP

.PP
Definition at line 1099 of file mkgentoo\&.sh\&.
.SS "manpage ()"

.PP
Print help to man page\&. 
.PP
Definition at line 234 of file mkgentoo\&.sh\&.
.SS "mount_live_cd ()"

.PP
Mount Gentoo/Clonezilla live CD and unsquashfs the GNU/linux system\&. 
.PP
\fBNote\fP
.RS 4
live CD is mounted under $VMPATH/mnt and rsync'd to $VMPATH/mnt2 
.RE
.PP

.PP
Definition at line 784 of file mkgentoo\&.sh\&.
.SS "pdfpage ()"

.PP
Print help to pdf page\&. 
.PP
Definition at line 252 of file mkgentoo\&.sh\&.
.SS "prepare_for_iso_vm ()"
Short version of \fBadd_guest_additions_to_clonezilla_iso\fP when the ISO has already been pre-authored\&. 
.PP
\fBNote\fP
.RS 4
Installing the guest additions is a prerequisite to folder sharing between the ISO VM and the host\&. Folder sharing is necessary to recover a compressed clonezilla image of the VDI virtual disk into the directory ISOFILES/home/partimag/image 
.RE
.PP

.PP
Definition at line 2304 of file mkgentoo\&.sh\&.
.SS "test_cli (cli)"

.PP
Analyse commandline\&. 
.PP
\fBParameters\fP
.RS 4
\fIcli\fP Commandline
.RE
.PP
.PD 0
.IP "\(bu" 2
Create globals of the form VAR=arg when there is var=arg on commandline 
.IP "\(bu" 2
Otherwise assign default values VAR=defaults (3rd argument in array \fBARR\fP) 
.IP "\(bu" 2
Also checks type of argument against types described for \fBARR\fP 
.PP

.PP
Definition at line 467 of file mkgentoo\&.sh\&.
.SS "test_cli_post ()"

.PP
Check commanline coherence and incompatibilities\&. 
.PP
\fBReturn values\fP
.RS 4
\fI0\fP or exit 1 on incompatibilities 
.RE
.PP

.PP
Definition at line 621 of file mkgentoo\&.sh\&.
.SS "test_cli_pre ()"

.PP
Check VirtualBox version and prepare commandline analysis\&. 
.PP
\fBReturn values\fP
.RS 4
\fI0\fP otherwise exit 1 if VirtualBox is too old 
.RE
.PP

.PP
Definition at line 353 of file mkgentoo\&.sh\&.
.SS "test_vm_running (vm)"

.PP
Check if VM as first named argument exists and is running\&. 
.PP
\fBParameters\fP
.RS 4
\fIvm\fP VM name or UUID 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIReturns\fP 0 on success and 1 is VM is not listed or not running 
.RE
.PP

.PP
Definition at line 1206 of file mkgentoo\&.sh\&.
.SS "unmount_clonezilla_iso ()"

.PP
Unmount the clonezilla filesystem after exiting chroot\&. Restore the squashfs filesystem\&. 
.PP
Definition at line 2187 of file mkgentoo\&.sh\&.
.SS "validate_option (option)"

.PP
Check if argument is part of array \fBARR\fP as a legitimate commandline option\&. 
.PP
\fBParameters\fP
.RS 4
\fIoption\fP String of option\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if legitimate option otherwise false\&. 
.RE
.PP

.PP
Definition at line 268 of file mkgentoo\&.sh\&.
.SH "Variable Documentation"
.PP 
.SS "ARR"

.PP
global string array of switches and default values Structure is as follows:
.PP
.nf
{{"Commandline option", "Description", "Default value", "Type"}, {\&.\&.\&.},\&.\&.\&.}

.fi
.PP
 'Type' is among the following values: 
.PD 0

.IP "\(bu" 2
\fBb\fP Boolean, 'false' or 'true' 
.IP "\(bu" 2
\fBd\fP An existing directory 
.IP "\(bu" 2
\fBe\fP Email address: regexp '[a-z]+@[a-z]+\\\&.[a-z]+' 
.IP "\(bu" 2
\fBf\fP An existing file 
.IP "\(bu" 2
\fBn\fP Numeric value 
.IP "\(bu" 2
\fBo\fP 'on' or 'off', a VBoxManage custom Boolean 
.IP "\(bu" 2
\fBs\fP Non-empty string\&. Corresponding defaults may be empty however\&. This is the notably case for passwords\&. For such options, explicit commandline value after '=' is requested\&. 
.IP "\(bu" 2
\fBu\fP Url 
.IP "\(bu" 2
\fBx:y\fP Conditional type x: one of the above, with [ -z '$x' ] <=> { [ '$y' = 'false' ] || [ -z '$y' ]; } && [ '$y' != 'true' ] 
.IP "\(bu" 2
\fBvm\fP Restricted to the \fCvm\fP option: can be set to @ code \fCfalse\fP to bypass OS building and only perform burning/external device operations\&. A double-entry array will be simulated using indexes\&.
.PP
\fBNote\fP
.RS 4
\fCdebug_mode\fP should be place up front in the array 
.RE
.PP

.PP
Definition at line 81 of file utils\&.sh\&.
.SS "Exported String CREATE_ISO = false"

.PP
Custom name of ISO output\&. Default value is false Can be reversed by a name of type filename\&.iso on command line, previously created and reused to burn or dd to device installer\&. 
.PP
Definition at line 113 of file mkgentoo\&.sh\&.
.SS "ISO = 'downloaded\&.iso'"

.PP
Name of downloaded clonezilla ISO file\&. 
.PP
Definition at line 105 of file mkgentoo\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
