.TH "fetch_clonezilla_iso.sh" 3 "Fri Oct 16 2020" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetch_clonezilla_iso.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_gentoo_install_iso\fP ()"
.br
.RI "Download minimal Gentoo install ISO file and caches\&. "
.ti -1c
.RI "\fBget_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO file and caches it\&. "
.ti -1c
.RI "\fBget_cache_clonezilla_iso\fP ()"
.br
.RI "Either download clonezilla ISO file and caches it OR uncaches it\&. "
.ti -1c
.RI "\fBfetch_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO file and process it\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBLIVECD\fP = ${\fBISO\fP}"
.br
.ti -1c
.RI "Exported String \fBCLONEZILLACD\fP = ${clonezilla_iso}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String CLONEZILLACD = ${clonezilla_iso}"

.PP
Definition at line 61 of file fetch_clonezilla_iso\&.sh\&.
.SS "Exported String LIVECD = ${\fBISO\fP}"

.PP
Definition at line 34 of file fetch_clonezilla_iso\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gentoo-creator from the source code\&.
