.TH "fetch_clonezilla_iso.sh" 3 "Sun Oct 4 2020" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetch_clonezilla_iso.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_gentoo_install_iso\fP ()"
.br
.RI "Download minimal Gentoo install ISO file and caches\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBLIVECD\fP = ${\fBISO\fP}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String LIVECD = ${\fBISO\fP}"

.PP
Definition at line 29 of file fetch_clonezilla_iso\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gentoo-creator from the source code\&.
