.TH "fetch_clonezilla_iso.sh" 3 "Thu Oct 1 2020" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetch_clonezilla_iso.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfetch_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO file and process it\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for gentoo-creator from the source code\&.
