.TH "mkgentoo.sh" 3 "Mon Mar 15 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mkgentoo.sh \- Process options, create Gentoo VirtualBox machine and optionally create clonezilla install medium\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhelp_md\fP ()"
.br
.RI "Print usage in markdown format\&. "
.ti -1c
.RI "\fBhelp_\fP ()"
.br
.RI "Print usage to stdout\&. "
.ti -1c
.RI "\fBmanpage\fP ()"
.br
.RI "Print help to man page\&. "
.ti -1c
.RI "\fBhtmlpage\fP ()"
.br
.RI "Print help to html page\&. "
.ti -1c
.RI "\fBpdfpage\fP ()"
.br
.RI "Print help to pdf page\&. "
.ti -1c
.RI "\fBvalidate_option\fP (option)"
.br
.RI "Check if argument is part of array \fBARR\fP as a legitimate commandline option\&. "
.ti -1c
.RI "\fBget_options\fP ()"
.br
.RI "Parse command line\&. "
.ti -1c
.RI "\fBtest_cli_pre\fP ()"
.br
.RI "Check VirtualBox version and prepare commandline analysis\&. "
.ti -1c
.RI "\fBtest_cli\fP (cli)"
.br
.RI "Analyse commandline\&. "
.ti -1c
.RI "\fBtest_cli_post\fP ()"
.br
.RI "Check commanline coherence and incompatibilities\&. "
.ti -1c
.RI "\fBmount_live_cd\fP ()"
.br
.RI "Mount Gentoo/Clonezilla live CD and unsquashfs the GNU/linux system\&. "
.ti -1c
.RI "\fBmove_auxiliary_files\fP ()"
.br
.ti -1c
.RI "\fBmake_boot_from_livecd\fP ()"
.br
.RI "Tweak the Gentoo minimal install CD so that the custom- made shell scripts and stage3 archive are included into the squashfs filesystem\&. "
.ti -1c
.RI "\fBprepare_bash_rc\fP ()"
.br
.ti -1c
.RI "\fBtest_vm_running\fP (vm)"
.br
.RI "Check if VM as first named argument exists and is running\&. "
.ti -1c
.RI "\fBdeep_clean\fP ()"
.br
.RI "Force-clean root VirtualBox registry\&. "
.ti -1c
.RI "\fBdelete_vm\fP (vm, ext)"
.br
.RI "Powers off, possibly with emergency stop, the VM names as first argument\&. "
.ti -1c
.RI "\fBcreate_vm\fP ()"
.br
.RI "Create main VirtualBox machine using VBoxManage commandline\&. "
.ti -1c
.RI "\fBlog_loop\fP ()"
.br
.RI "Loop log tags every minute and optionally plot virtual disk size\&. "
.ti -1c
.RI "\fBcreate_iso_vm\fP ()"
.br
.RI "Create the new VirtualBox machine aimed at converting the VDI virtualdisk containing the Gentoo Linux distribution into an XZ-compressed clonezilla image uneder \fBISOFILES/home/partimag/image\fP\&. "
.ti -1c
.RI "\fBclone_vm_to_device\fP (mode)"
.br
.RI "Directly clone Gentoo VM to USB stick (or any using block device) "
.ti -1c
.RI "\fBclone_vm_to_raw\fP ()"
.br
.RI "Use\&. "
.ti -1c
.RI "\fBdd_to_usb\fP ()"
.br
.RI "Bare-metal copy of temporary RAW disk to external device\&. "
.ti -1c
.RI "\fBvbox_img_works\fP ()"
.br
.RI "Test if \fBvbox-img\fP is functional\&. "
.ti -1c
.RI "\fBcreate_device_system\fP (Mode)"
.br
.RI "Clone VDI virtual disk to external device (USB device or hard drive) "
.ti -1c
.RI "\fBgenerate_Gentoo\fP ()"
.br
.RI "Launch routines: fetch install IO, starge3 archive, create VM\&. "
.ti -1c
.RI "\fBclonezilla_to_iso\fP (iso, dir)"
.br
.RI "Create Gentoo linux clonezilla ISO installer out of a clonezilla directory structure and an clonezilla image\&. "
.ti -1c
.RI "\fBadd_guest_additions_to_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO or recover it from cache calling \fBfetch_process_clonezilla_iso\fP\&. 
.br
Upgrade it with virtualbox guest additions\&. "
.ti -1c
.RI "\fBbind_mount_clonezilla_iso\fP ()"
.br
.RI "Fetches the clonezilla ISO\&. mount it to mnt, rsync it to mnt2 and ISOFILES bind-mount mnt2 live filesystem after unsquashfs\&. "
.ti -1c
.RI "\fBunmount_clonezilla_iso\fP ()"
.br
.RI "Unmount the clonezilla filesystem after exiting chroot\&. Restore the squashfs filesystem\&. "
.ti -1c
.RI "\fBclonezilla_device_to_image\fP ()"
.br
.RI "Create CloneZilla xz-compressed image out of an external block device (like a USB stick) "
.ti -1c
.RI "\fBprepare_for_iso_vm\fP ()"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Main function launching routines\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBISO\fP = 'downloaded\&.iso'"
.br
.RI "Name of downloaded clonezilla ISO file\&. "
.ti -1c
.RI "Exported String \fBCREATE_ISO\fP = false"
.br
.RI "Custom name of ISO output\&. Default value is false Can be reversed by a name of type filename\&.iso on command line, previously created and reused to burn or dd to device installer\&. "
.ti -1c
.RI "Exported String \fBLOG\fP"
.br
.ti -1c
.RI "Exported String \fBISOLINUX_DIR\fP = isolinux"
.br
.ti -1c
.RI "Exported String \fBPATH\fP = '${PATH}':'${VBPATH}'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Process options, create Gentoo VirtualBox machine and optionally create clonezilla install medium\&. 


.PP
\fBAuthor\fP
.RS 4
Fabrice Nicol fabrnicol@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
GPL v\&.3 
.RE
.PP
\fBNote\fP
.RS 4
This file is not included into the clonezilla ISO liveCD\&. 
.RE
.PP
\fBUSAGE\fP
.RS 4

.PP
.nf
mkg  [[switch=argument]\&.\&.\&.]  filename\&.iso  [1]
mkg  [[switch=argument]\&.\&.\&.]                [2]
mkg  help[=md]                             [3]

.fi
.PP
 
.RE
.PP
\fB\fP
.RS 4
Usage [1] creates a bootable ISO output file with a current Gentoo distribution\&. 
.br
Usage [2] creates a VirtualBox VDI dynamic disk and a virtual machine with name Gentoo\&. 
.br
Usage [3] prints this help, in markdown form if argument 'md' is specified\&. 
.br
.RE
.PP
\fB\fP
.RS 4
Run:
.PP
.nf
mkg help 

.fi
.PP
 to print a list of possible switches and arguments\&. 
.RE
.PP
\fBWarning\fP
.RS 4
you should have at least 55 GB of free disk space in the current directory or in vmpath if specified\&. Boolean values are either 'true' or 'false'\&. An option no followed by '=' is equivalent to \fBoption=true\fP, except for help and a possible ISO file\&. For example, to build a minimal: distribution,specify \fCminimal\fP or \fC minimal=true\fP on command line\&. 
.RE
.PP
\fB\fBExamples\fP:\fP
.RS 4

.PD 0

.IP "\(bu" 2
Only create the VM and virtual disk, in debug mode, without R and set new passwords, for a French-language platform\&. Use 8 cores\&. 
.PP
.nf
 mkg vm_language=fr minimal debug_mode ncpus=8
nonroot_user=ken passwd='util!Hx&32F' rootpasswd='Hk_32!_CD' cleanup=false

.fi
.PP
 
.IP "\(bu" 2
Create ISO clonezilla image of Gentoo linux, burn it to DVD, create an installed OS on a USB stick whose model label starts with \fIPNY\fP and finally create a clonezilla installer on another USB stick mounted under \fC /media/ken/AA45E \fP 
.PP
.nf
 mkgento burn hot_install ext_device="PNY" device_installer
ext_device="Sams" my_gentoo_image\&.iso

.fi
.PP
 
.PP
.RE
.PP

.PP
Definition in file \fBmkgentoo\&.sh\fP\&.
.SH "Function Documentation"
.PP 
.SS "move_auxiliary_files ()"

.PP
Definition at line 1010 of file mkgentoo\&.sh\&.
.SS "prepare_bash_rc ()"
Prepare the \&.bashrc file by exporting the environment this will be placed under /root in the VM 
.PP
Definition at line 1146 of file mkgentoo\&.sh\&.
.SH "Variable Documentation"
.PP 
.SS "Exported String ISOLINUX_DIR = isolinux"

.PP
Definition at line 950 of file mkgentoo\&.sh\&.
.SS "Exported String LOG"

.PP
Definition at line 279 of file mkgentoo\&.sh\&.
.SS "Exported String PATH = '${PATH}':'${VBPATH}'"

.PP
Definition at line 1357 of file mkgentoo\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
