.TH "mkgentoo.sh" 3 "Sun Feb 14 2021" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mkgentoo.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhelp_md\fP ()"
.br
.RI "Print usage in markdown format\&. "
.ti -1c
.RI "\fBhelp_\fP ()"
.br
.RI "Print usage to stdout\&. "
.ti -1c
.RI "\fBvalidate_option\fP (option)"
.br
.RI "Check if argument is part of array \fBARR\fP as a legitimate commandline option\&. "
.ti -1c
.RI "\fBtest_cli_pre\fP ()"
.br
.RI "Check VirtualBox version and prepare commandline analysis\&. "
.ti -1c
.RI "\fBtest_cli\fP (cli)"
.br
.RI "Analyse commandline\&. "
.ti -1c
.RI "\fBtest_cli_post\fP ()"
.br
.RI "Check commanline coherence and incompatibilities\&. "
.ti -1c
.RI "\fBfetch_livecd\fP ()"
.br
.RI "Downloads Gentoo install CD\&. "
.ti -1c
.RI "\fBfetch_stage3\fP ()"
.br
.RI "Downloads a fresh stage3 Gentoo archive\&. "
.ti -1c
.RI "\fBmount_live_cd\fP ()"
.br
.RI "Mount Gentoo/Clonezilla live CD and unsquashfs the GNU/linux system\&. "
.ti -1c
.RI "\fBmake_boot_from_livecd\fP ()"
.br
.RI "Tweak the Gentoo minimal install CD so that the custom- made shell scripts and stage3 archive are included into the squashfs filesystem\&. "
.ti -1c
.RI "\fBtest_vm_running\fP (vm)"
.br
.RI "Check if VM as first named argument exists and is running\&. "
.ti -1c
.RI "\fBdeep_clean\fP ()"
.br
.RI "Force-clean root VirtualBox registry\&. "
.ti -1c
.RI "\fBdelete_vm\fP (vm, ext)"
.br
.RI "Powers off, possibly with emergency stop, the VM names as first argument\&. "
.ti -1c
.RI "\fBcreate_vm\fP ()"
.br
.RI "Create main VirtualBox machine using VBoxManage commandline\&. "
.ti -1c
.RI "\fBclonezilla_to_iso\fP (iso, dir)"
.br
.RI "Create Gentoo linux clonezilla ISO installer out of a clonezilla directory structure and an clonezilla image\&. "
.ti -1c
.RI "\fBprocess_clonezilla_iso\fP ()"
.br
.RI "Download clonezilla ISO or recover it from cache calling \fBfetch_clonezilla_iso\fP\&. 
.br
Upgrade it with virtualbox guest additions\&. "
.ti -1c
.RI "\fBbuild_virtualbox\fP ()"
.br
.RI "Build VirtualBox from source using an unsquashed clonezilla CD as a chrooted environment\&. "
.ti -1c
.RI "\fBcreate_iso_vm\fP ()"
.br
.RI "Create the new VirtualBox machine aimed at converting the VDI virtualdisk containing the Gentoo Linux distribution into an XZ-compressed clonezilla image uneder \fBISOFILES/home/partimag/image\fP\&. "
.ti -1c
.RI "\fBclone_vm_to_device\fP ()"
.br
.RI "Directly clone Gentoo VM to USB stick (or any using block device) "
.ti -1c
.RI "\fBclone_vm_to_raw\fP ()"
.br
.RI "Use\&. "
.ti -1c
.RI "\fBdd_to_usb\fP ()"
.br
.RI "Bare-metal copy of temporary RAW disk to external device\&. "
.ti -1c
.RI "\fBclonezilla_device_to_image\fP ()"
.br
.RI "Create CloneZilla xz-compressed image out of an external block device (like a USB stick) "
.ti -1c
.RI "\fBvbox_img_works\fP ()"
.br
.RI "Test if \fBvbox-img\fP is functional\&. "
.ti -1c
.RI "\fBcreate_device_system\fP ()"
.br
.RI "Clone VDI virtual disk to external device (USB device or hard drive) "
.ti -1c
.RI "\fBcleanup\fP ()"
.br
.RI "Clean up all temporary files and directpries (except for VirtualBox build) "
.ti -1c
.RI "\fBgenerate_Gentoo\fP ()"
.br
.RI "Launch routines: fetch install IO, starge3 archive, create VM\&. "
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Main function launching routines\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ReadOnly String Array \fBARR\fP"
.br
.RI "global string array of switches and default values "
.ti -1c
.RI "ReadOnly Integer \fBARRAY_LENGTH\fP = $((${#\fBARR\fP[*]}/4))"
.br
.RI "Number of switches (true length of array divided by 4) "
.ti -1c
.RI "Exported String \fBCREATE_ISO\fP = false"
.br
.ti -1c
.RI "Exported String \fBLOG\fP"
.br
.ti -1c
.RI "Exported String \fBISO\fP = 'downloaded\&.iso'"
.br
.RI "Name of downloaded clonezilla ISO file\&. "
.ti -1c
.RI "Exported String \fBISOLINUX_DIR\fP = isolinux"
.br
.ti -1c
.RI "Exported String \fBPATH\fP = '${PATH}':'${VBPATH}'"
.br
.ti -1c
.RI "Exported String \fBDEBIAN_FRONTEND\fP = noninteractive"
.br
.ti -1c
.RI "Exported String \fBLD_LIBRARY_PATH\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String CREATE_ISO = false"

.PP
Definition at line 202 of file mkgentoo\&.sh\&.
.SS "Exported String DEBIAN_FRONTEND = noninteractive"

.PP
Definition at line 1420 of file mkgentoo\&.sh\&.
.SS "Exported String ISOLINUX_DIR = isolinux"

.PP
Definition at line 761 of file mkgentoo\&.sh\&.
.SS "Exported String LD_LIBRARY_PATH"
\fBInitial value:\fP
.PP
.nf
= "virtualbox/VirtualBox/out/linux\&.amd64/release/bin/\;








Exported String LD_LIBRARY_PATH = "virtualbox/VirtualBox/out/linux\&.amd64/release/bin/\
.fi
.PP
Definition at line 1482 of file mkgentoo\&.sh\&.
.SS "Exported String LOG"

.PP
Definition at line 212 of file mkgentoo\&.sh\&.
.SS "Exported String PATH = '${PATH}':'${VBPATH}'"

.PP
Definition at line 1092 of file mkgentoo\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for gentoo-creator from the source code\&.
