.TH "mkvm_chroot.sh" 3 "Fri Feb 19 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mkvm_chroot.sh \- Creating Gentoo filesystem in virtual disk\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBadjust_environment\fP ()"
.br
.ti -1c
.RI "\fBbuild_kernel\fP ()"
.br
.ti -1c
.RI "\fBinstall_software\fP ()"
.br
.ti -1c
.RI "\fBglobal_config\fP ()"
.br
.ti -1c
.RI "\fBfinalize\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Integer \fBres\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creating Gentoo filesystem in virtual disk\&. 


.PP
\fBAuthor\fP
.RS 4
Fabrice Nicol 
.RE
.PP
\fBCopyright\fP
.RS 4
GPL v\&.3 
.RE
.PP
\fBNote\fP
.RS 4
This file is included into the clonezilla ISO liveCD, then copied to the root of the virtual disk\&. 
.RE
.PP

.PP
Definition in file \fBmkvm_chroot\&.sh\fP\&.
.SH "Function Documentation"
.PP 
.SS "finalize ()"

.PP
Definition at line 355 of file mkvm_chroot\&.sh\&.
.SH "Variable Documentation"
.PP 
.SS "Integer res = 0"

.PP
Definition at line 396 of file mkvm_chroot\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
