.TH "run_mount_shared_dir.sh" 3 "Sun Mar 21 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
run_mount_shared_dir.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBSHARED_ROOT_DIR\fP = '${SHARED_DIR}'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String SHARED_ROOT_DIR = '${SHARED_DIR}'"

.PP
Definition at line 12 of file run_mount_shared_dir\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
