.TH "todo" 3 "Fri Oct 16 2020" "Version 1.0" "gentoo-creator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBcreate_vm\fP ()\fP" 1c
Find a way to only compact on success and never on failure of VM\&.  
.IP "\fBGlobal \fBmain\fP ()\fP" 1c
Daemonize the part below generate_Gentoo when #VMTYPE is \fCheadless\fP so that the script can be detached completely with \fCnohup mkgentoo \&.\&.\&. &\fP  
.IP "\fBGlobal \fBadjust_environment\fP ()\fP" 1c
Add more regional options by parametrization of commandline  
.IP "\fBGlobal \fBinstall_software\fP ()\fP" 1c
Add a script to build R dependencies 
.PP

