.TH "todo" 3 "Tue Sep 29 2020" "Version 1.0" "mkgentoo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBadjust_environment\fP ()\fP" 1c
Add more regional options by parametrization of commandline  
.IP "\fBGlobal \fBcreate_vm\fP ()\fP" 1c
Find a way to only compact on success and never on failure of VM\&.  
.IP "\fBGlobal \fBinstall_software\fP ()\fP" 1c
Add a script to build R dependencies 
.PP

