.TH "utils.sh" 3 "Thu Feb 18 2021" "Version 1.0" "mkg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.sh \- Auxiliary functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "declare i \fBARRAY_LENGTH\fP \fBcreate_options_array\fP ()"
.br
.RI "Read file \fBoptions\fP into a temporary array A which will contain command line specifications\&. "
.ti -1c
.RI "\fBcheck_md5sum\fP (filename)"
.br
.RI "Check md5sums in file MD5SUMS\&. "
.ti -1c
.RI "\fBtest_numeric\fP (number)"
.br
.RI "Test whether the input value is numeric\&. "
.ti -1c
.RI "\fBtest_URL\fP (Internet)"
.br
.RI "Test whether the input value is a valid URL\&. "
.ti -1c
.RI "\fBtest_email\fP (Email)"
.br
.RI "Test whether the input value is a valid email address\&. "
.ti -1c
.RI "\fBsend_mail\fP ()"
.br
.RI "Send an email to $EMAIL at $SMTP_URL to warn about end of processing\&. "
.ti -1c
.RI "\fBtest_cdrecord\fP ()"
.br
.ti -1c
.RI "\fBrecreate_liveCD_ISO\fP (dir)"
.br
.RI "Create ISO of liveCD out of directory\&. "
.ti -1c
.RI "\fBburn_iso\fP ()"
.br
.RI "Burn Gentoo clonezilla installer to DVD using \fBcdrecord\fP\&. "
.ti -1c
.RI "\fBcreate_install_ext_device\fP ()"
.br
.RI "Create USB-stick (or any external device) Gentoo clonezilla installer\&. "
.ti -1c
.RI "\fBcheck_dir\fP ()"
.br
.RI "Checks existence of directories\&. "
.ti -1c
.RI "\fBcheck_file\fP ()"
.br
.RI "Checks existence of file\&. "
.ti -1c
.RI "\fBcheck_files\fP ()"
.br
.RI "Checks existence of files\&. "
.ti -1c
.RI "\fBcheck_tool\fP ()"
.br
.RI "Checks existence of auxiliary tools\&. "
.ti -1c
.RI "\fBif_fails\fP ()"
.br
.RI "Echoes a message and exit in case of previous command failure\&. "
.ti -1c
.RI "\fBcleanup\fP ()"
.br
.RI "Clean up all temporary files and directpries (except for VirtualBox build) "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBARR\fP"
.br
.RI "global string array of switches and default values "
.ti -1c
.RI "Exported String \fBARRAY_LENGTH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Auxiliary functions\&. 


.PP
\fBAuthor\fP
.RS 4
Fabrice Nicol fabrnicol@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
GPL v\&.3 
.RE
.PP
\fBNote\fP
.RS 4
This file is not included into the clonezilla ISO liveCD\&. 
.RE
.PP

.PP
Definition in file \fButils\&.sh\fP\&.
.SH "Function Documentation"
.PP 
.SS "test_cdrecord ()"

.PP
Definition at line 258 of file utils\&.sh\&.
.SH "Variable Documentation"
.PP 
.SS "Exported String ARRAY_LENGTH"

.PP
Definition at line 82 of file utils\&.sh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for mkg from the source code\&.
