name: Gentoo.mkg.builder

on:
  push:
    branches: 
    - master 
    - gnome
  pull_request:
    branches: 
    - master 
    - gnome
  schedule:
  - cron: "0 2 * * 1-5"
  
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: update 
        run: |
             sudo apt update 
             sudo apt install uuid dos2unix
             sudo apt install squashfs-tools curl mkisofs cdrecord util-linux xorriso xz-utils
             sudo apt install virtualbox    
      
      - name: run
        run: |
          sudo ./mkg test_only
          
      - name: Upload Release Assets
        run: |
            set -x
            assets=()
            for asset in "./checksums.txt latest-install-amd64-minimal.txt latest-stage3-amd64.txt downloaded.iso"; do
            assets+=("-a" "$asset")
            done
            tag_name="${GITHUB_REF##*/}"
            hub release create  "${assets[@]}" \
            -m "Release $tag_name" \
            -m "This release was automatically created by the Git Actions workflow corresponding to directory .github in the repository." \
            -m "The output are the references of the latest stage3 archive and minimal Gentoo install ISO that were tested OK \
            for portage dependencies." \
            -m "File downloaded.iso is the custom MKG install ISO built from these references, to be used in a VirtualBox machine as an IDE optical device." \
            "$tag_name"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
